//
// Created by admin on 2026/2/4.
//

#ifndef INC_1_INPUT_H
#define INC_1_INPUT_H
#include <string>
#include <fstream>
#include <sstream>
#include <vector>
#include <Eigen/Dense>
#include <Eigen/Sparse>
using namespace std;

enum class Parity {
    Positive,
    Negative
};


// J-scheme orbit
struct Orbit {
    int n;
    int l;
    int j; // 2 * j
};

// M-scheme orbit
struct OrbitM {
    int n;
    int l;
    int j; // 2 * j
    int m; // 2 * m
};

// J-scheme pair
struct Pair {
    int index; // from 0
    int j; // 2 * j
    Parity parity;
    Eigen::MatrixXd yabr; // structure coefficient
};

// M-scheme pair
struct PairM {
    int index; // from 0
    int j; // 2 * j
    int m; // 2 * m
    Parity parity;
    Eigen::SparseMatrix<double, Eigen::RowMajor> pab; // structure coefficient
};

// new pair generated by commutator
struct PairNew {
    Eigen::SparseMatrix<double, Eigen::RowMajor> pab; // structure coefficient

    ~PairNew() = default;
};

// J-scheme limit of pair number
struct PairLimit {
    int limitMin;
    int limitMax;
    vector<int> indexes;
};

struct InteractionFile {
    string filename;
    int core;
    int A;
    double scale;
};

int readSps(const string& filename, int& orbitProtonNumber, int& orbitNeutronNumber,
    vector<Orbit*>& orbitProton, vector<Orbit*>& orbitNeutron);
int readInput(int& Z, int& N, string& spsFile, string& pairFile, int& interactionNumber,
    vector<InteractionFile*>& interactionFiles);
int readPair(const string& filename, int& pairTypes, vector<Pair*>& pairs, int& limitNumber,
    vector<PairLimit*>& limits);


#endif //INC_1_INPUT_H