//
// Created by admin on 2026/2/4.
//

#ifndef INC_1_INPUT_H
#define INC_1_INPUT_H
#include <string>
#include <fstream>
#include <sstream>
#include <vector>
#include <Eigen/Dense>
#include <Eigen/Sparse>
using namespace std;

enum class Parity {
    Positive,
    Negative
};


// J-scheme orbit
struct Orbit {
    int n;
    int l;
    int j; // 2 * j
    double spe;
};

// M-scheme orbit
struct OrbitM {
    int n;
    int l;
    int j; // 2 * j
    int m; // 2 * m
    double spe;
};

// J-scheme pair
struct Pair {
    int index; // from 0
    int j; // 2 * j
    Parity parity;
    Eigen::MatrixXd yabr; // structure coefficient
};

// M-scheme pair
struct PairM {
    int index; // from 0
    int j; // 2 * j
    int m; // 2 * m
    Parity parity;
    Eigen::SparseMatrix<double, Eigen::RowMajor> pab; // structure coefficient
};

// new pair generated by commutator
struct PairNew {
    Eigen::SparseMatrix<double, Eigen::RowMajor> pab; // structure coefficient

    ~PairNew() = default;
};

// J-scheme limit of pair number
struct PairLimit {
    int limitMin;
    int limitMax;
    vector<int> indexes;
};

struct InteractionFile {
    string filename;
    int core;
    int A;
    double scale;
};

struct TBMEJ {
    int a;
    int b;
    int c;
    int d;

    auto operator<=>(const TBMEJ&) const = default;
};

struct TBMEJHash {
    std::size_t operator()(const TBMEJ& k) const {
        std::size_t h1 = std::hash<int>{}(k.a);
        std::size_t h2 = std::hash<int>{}(k.b);
        std::size_t h3 = std::hash<int>{}(k.c);
        std::size_t h4 = std::hash<int>{}(k.d);

        // 经典的哈希组合方式，避免对称值（如 a=1,b=2 和 a=2,b=1）哈希冲突
        return h1 ^ (h2 << 1) ^ (h3 << 2) ^ (h4 << 3);
    }
};

int readSps(const string& filename, int& orbitProtonNumber, int& orbitNeutronNumber,
    vector<Orbit*>& orbitProton, vector<Orbit*>& orbitNeutron);
int readInput(int& Z, int& N, string& spsFile, string& pairFile, int& interactionNumber,
    vector<InteractionFile*>& interactionFiles);
int readPair(const string& filename, int& pairTypes, vector<Pair*>& pairs, int& limitNumber,
    vector<PairLimit*>& limits);


#endif //INC_1_INPUT_H